apiVersion: v1
kind: Service
metadata:
  name: {{ with (include "n8n.fullname" .) }}{{ eq . "n8n"  | ternary "n8n-svc" . }}{{ end }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "n8n.selectorLabels" . | nindent 4 }}
