apiVersion: v1
stringData:
{{- if .Values.n8n.basicAuth}}
    N8N_BASIC_AUTH_USER: {{ .Values.n8n.basicAuthUser }}
    N8N_BASIC_AUTH_PASSWORD: {{ .Values.n8n.basicAuthPassword }}
{{- end }}
    N8N_ENCRYPTION_KEY: {{ .Values.n8n.encryptionKey }}
kind: Secret
metadata:
    creationTimestamp: null
    name: {{ include "n8n.envVarsSecretName" . }}
