name: Update n8n appVersion

on:
  repository_dispatch:
    types:
      - update_n8n_app_version

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Updates Chart.yaml appVersion
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.appVersion = "${{ github.event.client_payload.nextVersion }}"' 'charts/n8n/Chart.yaml'

      - name: Commit appVersion update
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: bump n8n appVersion to ${{ github.event.client_payload.nextVersion }}"
