name: Release Charts

on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - update_n8n_app_version

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Add repositories
        run: |
          for dir in $(ls -d charts/*/); do
            helm dependency list $dir 2> /dev/null | tail +2 | head -n -1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
          done

      - uses: redhat-cop/github-actions/set-helm-version@master
        if: github.event.client_payload.appVersion != null
        with:
          path: ./charts/n8n
          app_version: ${{ github.event.client_payload.appVersion }}

      - name: Commit changes caused by version bump
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "feat: bump chart appVersion to ${{ github.event.client_payload.appVersion }}"

      - name: Get next version
        id: get_next_version
        uses: thenativeweb/get-next-version@2.1.1

      - uses: redhat-cop/github-actions/set-helm-version@master
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        with:
          path: ./charts/n8n
          chart_version: ${{ steps.get_next_version.outputs.version }}

      - name: Commit changes caused by version bump
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: bump chart version to ${{ steps.get_next_version.outputs.version }}"
          tagging_message: "${{ steps.get_next_version.outputs.version }}"

      - name: Run chart-releaser
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
